Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/jammy64"
  config.vm.synced_folder ".", "/vagrant", disabled: true

  BRIDGE_IF = "wlx90de80b68883"  #  физический интерфейс LAN

  NODES = [
    {name: "k8s-m1", ip: "192.168.1.141", mem: 2048, cpus: 2},
    {name: "k8s-w1", ip: "192.168.1.145", mem: 2048, cpus: 2},
  ]

  NODES.each do |node|
    config.vm.define node[:name] do |n|
      n.vm.hostname = node[:name]
      n.vm.provider :virtualbox do |vb|
        vb.name   = node[:name]
        vb.memory = node[:mem]
        vb.cpus   = node[:cpus]
      end
      n.vm.network "public_network", ip: node[:ip], bridge: BRIDGE_IF
      n.vm.provision "shell", path: "provision-2vm-common.sh"
    end
  end
end
